spring:
  datasource:
    username: sa
    password:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    jpa:
      hibernate:
        ddl-auto: none

  flyway:
    url: jdbc:h2:mem:test;MODE=mySql;INIT=RUNSCRIPT FROM 'D:\\Users\\Chuno\\.ideaprojects\\exposedapi\\src\\test\\resources\\db.migration\\test.sql'
    user: sa
    password:
    baseline-on-migrate: true
